version: '3.7'

services:
  database:
    image: postgres
    container_name: copa_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=copadb
    volumes:
      - pgdata:/data/postgres
  app:
      build: .
      container_name: copa_server
      ports:
        - 3333:3333
      volumes:
        - .:/usr/app
      links:
        - database
      depends_on:
        - database

volumes:
  pgdata:
    driver: local

